// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ap1/users_info": {
            "get": {
                "description": "用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/user_api.UserInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/data/login_date": {
            "get": {
                "description": "用户登录数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据统计"
                ],
                "summary": "用户登录数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "0 七天内  1 一个月   2 一年",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data_api.DataCountResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/data/look_date": {
            "get": {
                "description": "文档浏览量数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据统计"
                ],
                "summary": "文档浏览量数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文档id，不传就是查全部的",
                        "name": "docID",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "0 七天内  1 一个月   2 一年",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data_api.DataCountResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/data/sum": {
            "get": {
                "description": "首页的求和数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据统计"
                ],
                "summary": "首页的求和数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data_api.DataSumResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/docs": {
            "post": {
                "description": "创建文档，创建成功之后，data=文档id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "创建文档",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/doc_api.DocCreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/docs/digg/{id}": {
            "get": {
                "description": "文档点赞",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "文档点赞",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/docs/edit/{id}": {
            "get": {
                "description": "获取完整的正文",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "获取完整的正文",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/doc_api.DocItemResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/docs/info/{id}": {
            "get": {
                "description": "文档基础信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "文档基础信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/doc_api.DocInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/docs/pwd": {
            "post": {
                "description": "输入密码，访问文档",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "输入密码，访问文档",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/doc_api.DocPwdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/doc_api.DocContentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/docs/search": {
            "get": {
                "description": "全文搜索",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "全文搜索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模糊匹配的关键字",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/res.ListResponse-models_FullTextModel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/docs/{id}": {
            "get": {
                "description": "文档内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "文档内容",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/doc_api.DocContentResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新文档，更新文档的标题和正文",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "更新文档",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/doc_api.DocUpdateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除文档",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文档管理"
                ],
                "summary": "删除文档",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/image": {
            "post": {
                "description": "上传图片",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "上传图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件上传",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/images": {
            "get": {
                "description": "图片列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "图片列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模糊匹配的关键字",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/res.ListResponse-image_api_ImageListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除图片",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片管理"
                ],
                "summary": "删除图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "用户登录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_api.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/logout": {
            "get": {
                "description": "用户注销",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户注销",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/logs": {
            "get": {
                "description": "日志列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志管理"
                ],
                "summary": "日志列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "感觉地址查询",
                        "name": "addr",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "查某一天，格式是年-月-日",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "根据ip查询",
                        "name": "ip",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "模糊匹配的关键字",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "Info",
                            "Warning",
                            "Error"
                        ],
                        "description": "日志查询的等级",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "登录状态查询  1  成功  2 失败",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "x-enum-varnames": [
                            "LoginType",
                            "ActionType",
                            "RuntimeType"
                        ],
                        "description": "日志的类型   1 登录日志  2 操作日志  3 运行日志",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "根据用户id查询",
                        "name": "userID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "查用户名",
                        "name": "userName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/res.ListResponse-log_stash_LogModel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除日志",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志管理"
                ],
                "summary": "删除日志",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/log_api.LogRemoveRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/logs/read": {
            "get": {
                "description": "日志列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "日志管理"
                ],
                "summary": "日志列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/role_docs": {
            "get": {
                "description": "角色文档树",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色文档管理"
                ],
                "summary": "角色文档树",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/role_doc_api.RoleDocTreeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "角色文档 更新",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色文档管理"
                ],
                "summary": "角色文档 更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_doc_api.RoleDocUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "添加一篇角色文档",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色文档管理"
                ],
                "summary": "添加一篇角色文档",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_doc_api.RoleDocRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除一篇角色文档",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色文档管理"
                ],
                "summary": "删除一篇角色文档",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_doc_api.RoleDocRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/role_docs/info": {
            "get": {
                "description": "角色文档信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色文档管理"
                ],
                "summary": "角色文档信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "docID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "绑定query时，对应标签是 form， 绑定form表单数据也是用 form标签",
                        "name": "roleID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/role_doc_api.RoleDocInfoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "角色文档信息 更新",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色文档管理"
                ],
                "summary": "角色文档信息 更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_doc_api.RoleDocInfoUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/role_docs/{id}": {
            "get": {
                "description": "文档树列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色文档管理"
                ],
                "summary": "文档树列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/role_doc_api.RoleDocListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/roles": {
            "get": {
                "description": "角色列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模糊匹配的关键字",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/res.ListResponse-role_api_RoleListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_api.RoleCreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role_api.RoleCreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.IDRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/roles/id": {
            "get": {
                "description": "角色id列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "角色id列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Options"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/site": {
            "get": {
                "description": "站点配置查询",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点配置"
                ],
                "summary": "站点配置查询",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/config.Site"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "站点配置更新",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点配"
                ],
                "summary": "站点配置更新",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/user_center/user_coll": {
            "get": {
                "description": "收藏文档列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "个人中心"
                ],
                "summary": "收藏文档列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/res.ListResponse-user_center_api_UserCollDocListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "收藏文档或取消收藏",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "个人中心"
                ],
                "summary": "收藏文档或取消收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.IDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "description": "用户列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模糊匹配的关键字",
                        "name": "key",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "roleID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/res.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/res.ListResponse-models_UserModel"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "管理员更新用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "管理员更新用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_api.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建用户，只能管理员创建",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_api.UserCreateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/users_info": {
            "put": {
                "description": "用户更新自己的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户更新自己的信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_api.UserUpdateInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        },
        "/api/users_password": {
            "put": {
                "description": "用户修改密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户修改密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user_api.UserUpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.Site": {
            "type": "object",
            "properties": {
                "abstract": {
                    "description": "网站简介",
                    "type": "string"
                },
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "footer": {
                    "description": "尾部信息",
                    "type": "string"
                },
                "href": {
                    "description": "点击go的跳转链接",
                    "type": "string"
                },
                "icon": {
                    "description": "首页的图标",
                    "type": "string"
                },
                "iconHref": {
                    "description": "图标链接",
                    "type": "string"
                },
                "title": {
                    "description": "网站名称",
                    "type": "string"
                }
            }
        },
        "data_api.DataCountResponse": {
            "type": "object",
            "properties": {
                "countList": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "dateList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "data_api.DataSumResponse": {
            "type": "object",
            "properties": {
                "diggCount": {
                    "description": "总点赞数",
                    "type": "integer"
                },
                "docCount": {
                    "description": "总文档树",
                    "type": "integer"
                },
                "lookCount": {
                    "description": "总浏览量",
                    "type": "integer"
                },
                "userCount": {
                    "description": "总用户数",
                    "type": "integer"
                }
            }
        },
        "doc_api.DocContentResponse": {
            "type": "object",
            "properties": {
                "collCount": {
                    "description": "收藏量",
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "diggCount": {
                    "description": "点赞量",
                    "type": "integer"
                },
                "isColl": {
                    "description": "用户是否收藏",
                    "type": "boolean"
                },
                "isPwd": {
                    "description": "是否需要密码",
                    "type": "boolean"
                },
                "isSee": {
                    "description": "是否试看",
                    "type": "boolean"
                },
                "lookCount": {
                    "description": "浏览量",
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "doc_api.DocCreateRequest": {
            "type": "object",
            "required": [
                "content",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "parentID": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "doc_api.DocInfoResponse": {
            "type": "object",
            "properties": {
                "contentLength": {
                    "description": "正文内容",
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "diggCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "lookCount": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "doc_api.DocItemResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "doc_api.DocPwdRequest": {
            "type": "object",
            "properties": {
                "docID": {
                    "description": "文档id",
                    "type": "integer"
                },
                "pwd": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "doc_api.DocUpdateRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "image_api.ImageListResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickName": {
                    "type": "string"
                },
                "path": {
                    "description": "update/xx.png",
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                },
                "webPath": {
                    "type": "string"
                }
            }
        },
        "log_api.LogRemoveRequest": {
            "type": "object",
            "properties": {
                "endTime": {
                    "description": "年月日格式的结束时间",
                    "type": "string"
                },
                "idList": {
                    "description": "可以传id列表删除",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "ip": {
                    "description": "根据用户ip删除",
                    "type": "string"
                },
                "startTime": {
                    "description": "年月日格式的开始时间",
                    "type": "string"
                },
                "userID": {
                    "description": "根据用户删除日志",
                    "type": "integer"
                }
            }
        },
        "log_stash.Level": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "Info",
                "Warning",
                "Error"
            ]
        },
        "log_stash.LogModel": {
            "type": "object",
            "properties": {
                "addr": {
                    "description": "地址",
                    "type": "string"
                },
                "content": {
                    "description": "详情",
                    "type": "string"
                },
                "createdAt": {
                    "description": "添加时间",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "ip": {
                    "description": "ip",
                    "type": "string"
                },
                "level": {
                    "description": "等级",
                    "allOf": [
                        {
                            "$ref": "#/definitions/log_stash.Level"
                        }
                    ]
                },
                "readStatus": {
                    "description": "阅读状态   true   已读  false  未读  默认是未读状态",
                    "type": "boolean"
                },
                "serviceName": {
                    "description": "服务名称",
                    "type": "string"
                },
                "status": {
                    "description": "登录状态",
                    "type": "boolean"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "type": {
                    "description": "日志的类型  1 登录 2 操作 3 运行",
                    "allOf": [
                        {
                            "$ref": "#/definitions/log_stash.LogType"
                        }
                    ]
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                },
                "userID": {
                    "description": "用户id",
                    "type": "integer"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "log_stash.LogType": {
            "type": "integer",
            "enum": [
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "LoginType",
                "ActionType",
                "RuntimeType"
            ]
        },
        "models.FullTextModel": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "正文",
                    "type": "string"
                },
                "docID": {
                    "type": "integer"
                },
                "id": {
                    "description": "es的id",
                    "type": "string"
                },
                "slug": {
                    "description": "跳转地址，可以由docID和title拼接而来",
                    "type": "string"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "models.IDRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "models.Options": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "models.RoleModel": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isSystem": {
                    "description": "是否是系统角色",
                    "type": "boolean"
                },
                "pwd": {
                    "description": "统一设置这个角色所拥有的需要密码访问的文档的密码",
                    "type": "string"
                },
                "title": {
                    "description": "角色的名称",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.UserModel": {
            "type": "object",
            "properties": {
                "addr": {
                    "description": "地址",
                    "type": "string"
                },
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "description": "ip",
                    "type": "string"
                },
                "lastLogin": {
                    "description": "用户最后登录时间",
                    "type": "string"
                },
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                },
                "roleID": {
                    "description": "用户对应的角色",
                    "type": "integer"
                },
                "roleModel": {
                    "description": "用户角色信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.RoleModel"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "res.Code": {
            "type": "integer",
            "enum": [
                0,
                7,
                9
            ],
            "x-enum-comments": {
                "ErrorCode": "系统错误",
                "ValidCode": "校验错误"
            },
            "x-enum-varnames": [
                "SUCCESS",
                "ErrorCode",
                "ValidCode"
            ]
        },
        "res.ListResponse-image_api_ImageListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/image_api.ImageListResponse"
                    }
                }
            }
        },
        "res.ListResponse-log_stash_LogModel": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/log_stash.LogModel"
                    }
                }
            }
        },
        "res.ListResponse-models_FullTextModel": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.FullTextModel"
                    }
                }
            }
        },
        "res.ListResponse-models_UserModel": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserModel"
                    }
                }
            }
        },
        "res.ListResponse-role_api_RoleListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role_api.RoleListResponse"
                    }
                }
            }
        },
        "res.ListResponse-user_center_api_UserCollDocListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user_center_api.UserCollDocListResponse"
                    }
                }
            }
        },
        "res.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/res.Code"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "role_api.RoleCreateRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "pwd": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2
                }
            }
        },
        "role_api.RoleListResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "docCount": {
                    "description": "角色拥有的文档数",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isSystem": {
                    "description": "是否是系统角色",
                    "type": "boolean"
                },
                "pwd": {
                    "description": "统一设置这个角色所拥有的需要密码访问的文档的密码",
                    "type": "string"
                },
                "title": {
                    "description": "角色的名称",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userCount": {
                    "description": "角色下的用户数",
                    "type": "integer"
                }
            }
        },
        "role_doc_api.DocItem": {
            "type": "object",
            "properties": {
                "docID": {
                    "type": "integer"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "role_doc_api.DocTree": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role_doc_api.DocTree"
                    }
                },
                "isPwd": {
                    "description": "是否需要密码",
                    "type": "boolean"
                },
                "isSee": {
                    "description": "是否试看",
                    "type": "boolean"
                },
                "key": {
                    "type": "integer"
                },
                "show": {
                    "description": "角色是否可以看到文档",
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "role_doc_api.RoleDocInfoResponse": {
            "type": "object",
            "properties": {
                "freeContent": {
                    "description": "文档的试看内容",
                    "type": "string"
                },
                "isPwd": {
                    "description": "是否开启密码",
                    "type": "boolean"
                },
                "isSee": {
                    "description": "是否开启了试看",
                    "type": "boolean"
                },
                "roleDocPwd": {
                    "description": "角色文档的密码",
                    "type": "string"
                },
                "rolePwd": {
                    "description": "角色的密码",
                    "type": "string"
                }
            }
        },
        "role_doc_api.RoleDocInfoUpdateRequest": {
            "type": "object",
            "required": [
                "docID",
                "roleID"
            ],
            "properties": {
                "docID": {
                    "type": "integer"
                },
                "freeContent": {
                    "description": "文档的试看内容",
                    "type": "string"
                },
                "isPwd": {
                    "description": "是否开启密码",
                    "type": "boolean"
                },
                "isSee": {
                    "description": "是否开启了试看",
                    "type": "boolean"
                },
                "roleDocPwd": {
                    "description": "角色文档的密码",
                    "type": "string"
                },
                "roleID": {
                    "description": "绑定query时，对应标签是 form， 绑定form表单数据也是用 form标签",
                    "type": "integer"
                }
            }
        },
        "role_doc_api.RoleDocListResponse": {
            "type": "object",
            "properties": {
                "docIDList": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role_doc_api.DocTree"
                    }
                }
            }
        },
        "role_doc_api.RoleDocRequest": {
            "type": "object",
            "required": [
                "docID",
                "roleID"
            ],
            "properties": {
                "docID": {
                    "type": "integer"
                },
                "roleID": {
                    "description": "绑定query时，对应标签是 form， 绑定form表单数据也是用 form标签",
                    "type": "integer"
                }
            }
        },
        "role_doc_api.RoleDocTree": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role_doc_api.RoleDocTree"
                    }
                },
                "isColl": {
                    "description": "是否收藏",
                    "type": "boolean"
                },
                "isPwd": {
                    "description": "是否需要密码",
                    "type": "boolean"
                },
                "isSee": {
                    "description": "是否试看",
                    "type": "boolean"
                },
                "key": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "unlock": {
                    "description": "是否解锁",
                    "type": "boolean"
                }
            }
        },
        "role_doc_api.RoleDocTreeResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role_doc_api.RoleDocTree"
                    }
                }
            }
        },
        "role_doc_api.RoleDocUpdateRequest": {
            "type": "object",
            "required": [
                "roleID"
            ],
            "properties": {
                "docList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role_doc_api.DocItem"
                    }
                },
                "roleID": {
                    "type": "integer"
                }
            }
        },
        "user_api.UserCreateRequest": {
            "type": "object",
            "required": [
                "password",
                "roleID",
                "userName"
            ],
            "properties": {
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "roleID": {
                    "description": "角色id",
                    "type": "integer"
                },
                "userName": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "user_api.UserInfoResponse": {
            "type": "object",
            "properties": {
                "addr": {
                    "description": "地址",
                    "type": "string"
                },
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "description": "ip",
                    "type": "string"
                },
                "lastLogin": {
                    "description": "用户最后登录时间",
                    "type": "string"
                },
                "nickName": {
                    "description": "昵称",
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "roleID": {
                    "description": "用户对应的角色",
                    "type": "integer"
                },
                "roleModel": {
                    "description": "用户角色信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.RoleModel"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "user_api.UserLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "userName"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "user_api.UserUpdateInfoRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                }
            }
        },
        "user_api.UserUpdatePasswordRequest": {
            "type": "object",
            "required": [
                "oldPwd",
                "password"
            ],
            "properties": {
                "oldPwd": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "user_api.UserUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "password",
                "roleID"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nickName": {
                    "type": "string"
                },
                "password": {
                    "description": "bingding字段 定义字段在数据绑定（比如 HTTP 请求参数绑定）时的行为",
                    "type": "string"
                },
                "roleID": {
                    "description": "角色ID",
                    "type": "integer"
                }
            }
        },
        "user_center_api.UserCollDocListResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "什么时候收藏文档的",
                    "type": "string"
                },
                "diggCount": {
                    "description": "点赞量",
                    "type": "integer"
                },
                "docID": {
                    "description": "文档id",
                    "type": "integer"
                },
                "docUpdateTime": {
                    "description": "文档的更新时间",
                    "type": "string"
                },
                "isPermission": {
                    "description": "是否有文档的访问权限",
                    "type": "boolean"
                },
                "lookCount": {
                    "description": "浏览量",
                    "type": "integer"
                },
                "title": {
                    "description": "文档标题",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "文档项目api文档",
	Description:      "API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
